#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const emojiRegex = fs.readFileSync(path.join(__dirname, '../node_modules/emoji-test-regex-pattern/dist/latest/java.txt'), 'utf8')
                     .trim()
                     // replace incompatible escapes
                     .replace(/\\x\{([a-zA-Z0-9]{5})\}/g, '\\u{$1}')
                     .replace(/\\x\{([a-zA-Z0-9]{4})\}/g, '\\u$1')
                     .replace(/\\x([a-zA-Z0-9]{2})/g, '\\u00$1')

const input = fs.readFileSync(path.join(__dirname, '../src/emoji_regex.rb'), 'utf8');

const output = input.replace('/% emojiRegex %/', `/${emojiRegex}/`)

fs.writeFileSync(path.join(__dirname, '../lib/emoji_regex.rb'), output);
