name: Node & Ruby CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test Ruby ${{ matrix.ruby }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - '3.0'
          - head

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run Setup Script
      run: bin/setup

    - name: Regenerate code
      run: bundle exec rake regenerate

    - name: Run specs
      run: bundle exec rake
